---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian64
    box: capxilinx/debian64
    box_url: capxilinx/debian64

suites:
  - name: default
    run_list:
      - recipe[OpENer::default]
    attributes:
